### ISSUE TITLE
Error in cocaine-tornado-proxy

### ISSUE THREAD

**Issue by werehuman** [cocaine/cocaine-tools#29]
```
$ /usr/bin/cocaine-tornado-proxy --log_to_stderr
Traceback (most recent call last):
  File "/usr/bin/cocaine-tornado-proxy", line 9, in <module>
    load_entry_point('cocaine-tools==0.12.0.0rc28', 'console_scripts', 'cocaine-tornado-proxy')()
  File "/usr/lib/python2.7/dist-packages/cocaine/proxy/proxy.py", line 419, in main
    sticky_header=opts.sticky_header)
  File "/usr/lib/python2.7/dist-packages/tornado/util.py", line 215, in __new__
    instance.initialize(*args, **init_kwargs)
TypeError: initialize() got an unexpected keyword argument 'locators'
```

**Comment by noxiouz** [comment]
Tornado 4.2 broke API for HTTPServers. Also I see, that you used not so new version of proxy. Please, update to the latest one from master.
